AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  CloudFormation template to integrate EventBridge rule with Lambda
Resources:
  EventRule1:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      Name: test-eb-rule-once-per-month
      ScheduleExpression: cron(0 8 1 * ? *)
      State: ENABLED
      Targets:
        - Id: "replace_with_id"
          Arn: >-
            "lambda arn"
         
  PermissionForEvent0ToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: fahim-test
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "EventRule1"
          - "Arn"